#!/bin/bash
# A script that reads ebooks on the command line
 if [[ -z "$1" ]] ; then 
echo "Usage: ./epub.sh book.epub"
exit
fi
FILELIST=`zipinfo -1 "$1" | grep -E '(.xml|.html)' |sort`
TEXT=""
for FILE in $FILELIST
do 
TEXT="$TEXT `unzip -caa "$1" "$FILE" `"
done
echo $TEXT | lynx -stdin
