#!/bin/bash
#export TERM=xterm
#mate-terminal --command="cmatrix;bash"
#compton --config ~/.config/i3/compton.conf &
terminator -p cmatrix -f --command="TERM=xterm cmatrix" 
#terminator -e cmatrix 
#uxterm -e "cmatrix ; bash"
#sleep 0.2
i3lock -n; pkill cmatrix
#pkill compton

