#!/bin/bash

# Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license

set -e

pdf="$1"
file_name=

make_file() {
    #echo "${1%.*}.pdf"

cat >"$file_name" <<EOF

# Summary

# Quotes and Data

# Questions
EOF
}

check_file() {
    file="$HOME/Dropbox/Notes/Papers/${1%.*}.md"
    if [[ -f $file ]]; then
            file_name="$file"
    else
        file_name="$file"
        make_file "${1}"
    fi
}

check_file "${@}"
vim "$file_name"
