#!/bin/bash

# Author: Conner McDaniel
# https://github.com/connermcd/bin
# MIT license

set -e

pdf="$1"
file_name=

check_title() {
    doi="$(pdf2doi ${1})"
    echo "doi" $doi
    bib=$(curl -s "http://api.crossref.org/works/$doi/transform/application/x-bibtex")
    title=$(echo "$bib" | sed -n '1p' | cut -d{ -f2 | sed 's/,//')
}

make_file() {
    echo "${1%.*}.pdf" 
new_pdf="$(dirname $pdf)/${1%.*}.pdf"
# if a pdf with correct title doesnt exist rename current file with correct title
[[ ! -f "$new_pdf" ]] && mv "$pdf" "$new_pdf"
# update the bibliographic info with modified filename
bib=$(echo "$bib" | sed "1a\\\tpdf = {$new_pdf},")
# create a template file
cat >"$file_name" <<EOF
~~~.bib
$bib
~~~

# Summary

# Quotes and Data

# Questions
EOF
}

check_file() {
    file="$HOME/Documents/Notes/Papers/${1%.*}.md"
    if [[ -f $file ]]; then
        #file_doi=$(grep -o -E "doi = {[^}]*" $file | cut -d{ -f2)
        #if [[ "${file_doi,,}" =~ "${doi,,}" ]]; then
            file_name="$file"
        #else
            #check_file "${1}+"
        #fi
    else
        file_name="$file"
        check_title "$1"
        make_file "${1}"
    fi
}

check_file "${1}"
vim "$file_name"
