#!/bin/bash

# This script is for quickly opening up any pdf file
# this uses the results of find which has been cached to a text file

findresults="$HOME/.data/findpdfs.txt"
targ=$(cat $findresults | rofi -show -dmenu -i)

if [[ $targ != "" ]]; then
zathura "$targ" &
fi
