#!/bin/bash

#fd -e pdf -L | rofi -show file-browser-extended -file-browser-follow-symlinks -file-browser-stdin
notify-send "Indexing pdf files..."
findcmd="find -L $HOME/dbooks $HOME/Dropbox -type f -maxdepth 4 -iname '*.pdf' 2>/dev/null"
eval "$findcmd" | rofi -show file-browser-extended -file-browser-follow-symlinks -file-browser-stdin
