#!/bin/bash
# This script accepts a pattern and searches inside pdf files
# inside a defined base directory
# It shows the files that are matched
# and then a preview of the context
# and finally opens the pdf in your default viewer

basepath="$HOME/Dropbox/Research-DB"
pattern=$1
if [[ $pattern != "" ]]; then
    echo "searching for $pattern"
    pdffile=$(pdfgrep "$pattern" -r --max-count 1 -l --cache "$basepath" | fzf)
    echo $pdffile
    if [[ $pdffile != "" ]]; then
	pdfgrep "$pattern" --cache "$pdffile" | fzf
    devour xdg-open "$pdffile" && exit
    fi
fi
