#!/usr/bin/env python3
import arxiv
import os
import sys
import re

def get_valid_filename(s):
    """
    Return the given string converted to a string that can be used for a clean
    filename. Remove leading and trailing spaces; convert other spaces to
    underscores; and remove anything that is not an alphanumeric, dash,
    underscore, or dot.

    >>> get_valid_filename("john's portrait in 2004.jpg")
    'johns_portrait_in_2004.jpg'

    https://github.com/django/django/blob/master/django/utils/text.py
    Copyright (c) Django Software Foundation and individual contributors.
    All rights reserved.
    """
    s = str(s).strip().replace(' ', '_')
    return re.sub(r'(?u)[^-\w.]', '', s)

basename = os.path.basename(sys.argv[1])
dirname = os.path.dirname(sys.argv[1])
article_id = basename.strip('.pdf')

entry = arxiv.query(id_list=[article_id])
title = entry[0]['title']
title_slug = get_valid_filename(title)

new_basename = title_slug + '_' + basename
new_path = os.path.join(dirname, new_basename)

os.rename(sys.argv[1], new_path)
