#!/usr/bin/env sh
# A script for hiding and unhiding windows for use in dwm

appclass="telegram-desktop"
app="telegram-desktop"

#find  window id
wid=`xdotool search --classname "${appclass}"`
#if it is active app toggle its visibility
if [ $? -eq 0 ]; then
        #it is active but is it visible?
        widvisible=`xdotool search --onlyvisible --classname "${appclass}"`
        if [ $? -eq 0 ]; then
                #hide window
                xdotool windowunmap $wid
        else
                #show window
                xdotool windowmap $wid
        fi
else
        #start app
        "${app}" &
fi
