#!/bin/sh
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

#file="$HOME/.todo"
#touch "$file"
#height=$(wc -l "$file" | awk '{print $1}')
#prompt="Add/delete a task: "

#cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
#while [ -n "$cmd" ]; do
         #if grep -q "^$cmd\$" "$file"; then
		#grep -v "^$cmd\$" "$file" > "$file.$$"
		#mv "$file.$$" "$file"
        #height=$(( height - 1 ))
         #else
		#echo "$cmd" >> "$file"
		#height=$(( height + 1 ))
         #fi

	#cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
#done

#exit 0

#file="$HOME/.mytodo"
#touch "$file"
#height=$(wc -l "$file" | awk '{print $1}')
##cmd=$(dmenu -l 0 -p "Add task" "$@" < "$file")
#grep -v x .mytodo | dmenu  -p "Add task" -l "$height"
#val=$(grep -v x .mytodo | dmenu -p "Add task" -l 10)


		#echo "$cmd" >> "$file"
file="$HOME/Dropbox/todo/todo.txt"
height=$(wc -l "$file" | awk '{print $1}')
grep -v x "$file" | dmenu  -p "Your tasks" -l "$height"

