#!/bin/sh
cat > "$1.tex" <<EOF
\documentclass{article}
\usepackage[utf8]{inputenc}

\title{basic template}
\author{Linn Abraham}
\date{$(date "+%d %B %Y")}

\begin{document}

\maketitle

\section{Introduction}

\end{document}

EOF

vim "$1.tex"
